### ISSUE TITLE
Click on a timestamp, get a parse error on query

### ISSUE THREAD

**Issue by colohan** [kosak/z2kplus#29] opened 2023-09-16 19:08 UTC
1.  Go to any zgram.  Click on the timestamp link.  For example, [[Sep 16, 2023 12:02 PM](https://z2k.plus/static/chat.html?query=%5B%22%22%2C%5B%5B%22ts%22%2C1694890941%5D%5D%5D)] is one such link.
2.  Click "query" in the toolbar at the top, since you are curious what this has linked to.
3. In the dialog box that comes up, it will announce in red "Parse Error".

**Comment by kosak** [comment] 2023-09-16 23:07
Duplicate of https://github.com/kosak/z2kplus/issues/26

**Closed by kosak** 2023-09-16 23:07 UTC
